language: node_js
node_js:
  - 4
  - 6

cache:                                                                                                                                                                                                                                                                    
  yarn: true                                                                                                                                                                                                                                                              
  directories:                                                                                                                                                                                                                                                            
    - node_modules

after_success:
  - npm run report-coverage
